#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_101561

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_101561.PyCue_Ability_Loop_10156102
// 0x0000 (0x0E50 - 0x0E50)
class APyCue_Ability_Loop_10156102 final : public AMarvelCueNotify_Ability
{
public:
	void WhileActiveFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	bool OnRemove(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyCue_Ability_Loop_10156102">();
	}
	static class APyCue_Ability_Loop_10156102* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_Ability_Loop_10156102>();
	}
};

// PythonClass PyAbility_101561.PyBondEnhanceSourceResolver_101561
// 0x0000 (0x0030 - 0x0030)
class UPyBondEnhanceSourceResolver_101561 final : public UBondEnhanceSourceResolverBase
{
public:
	class AMarvelBaseCharacter* GetEnhanceSource(class AMarvelBaseCharacter* InOwnerCharacter, int32 InOwnerAbilityID, const struct FBondInstance& InBondInstance);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyBondEnhanceSourceResolver_101561">();
	}
	static class UPyBondEnhanceSourceResolver_101561* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyBondEnhanceSourceResolver_101561>();
	}
};

}

