#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyHumanTorchActor

#include "Basic.hpp"

#include "Hero_1017_classes.hpp"


namespace SDK
{

// PythonClass PyHumanTorchActor.PyHumanTorchChildActor
// 0x0000 (0x0DE0 - 0x0DE0)
class APyHumanTorchChildActor final : public AHumanTorchChildActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyHumanTorchChildActor">();
	}
	static class APyHumanTorchChildActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyHumanTorchChildActor>();
	}
};

// PythonClass PyHumanTorchActor.PyHumanTorchCharacter
// 0x0000 (0x18F0 - 0x18F0)
class APyHumanTorchCharacter : public AHumanTorchCharacter
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyHumanTorchCharacter">();
	}
	static class APyHumanTorchCharacter* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyHumanTorchCharacter>();
	}
};

}

