#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_LobbyHero

#include "Basic.hpp"

#include "PyWidget_LobbyChildPanel_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_LobbyHero.PyWidget_LobbyHero
// 0x0000 (0x0618 - 0x0618)
class UPyWidget_LobbyHero : public UPyWidget_LobbyChildPanel
{
public:
	void OnInitialized();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_LobbyHero">();
	}
	static class UPyWidget_LobbyHero* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_LobbyHero>();
	}
};

}

