#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_LobbyGalleryPanel

#include "Basic.hpp"

#include "PyWidget_LobbyChildPanel_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_LobbyGalleryPanel.PyWidget_LobbyGalleryPanel
// 0x0000 (0x0618 - 0x0618)
class UPyWidget_LobbyGalleryPanel : public UPyWidget_LobbyChildPanel
{
public:
	void OnInitialized();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_LobbyGalleryPanel">();
	}
	static class UPyWidget_LobbyGalleryPanel* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_LobbyGalleryPanel>();
	}
};

}

