#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Common_RankResult

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Common_RankResult.PyWidget_Common_RankResult
// 0x0000 (0x05F0 - 0x05F0)
class UPyWidget_Common_RankResult : public UPyMarvelUserWidget
{
public:
	void OnInitialized();
	void Construct();
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Common_RankResult">();
	}
	static class UPyWidget_Common_RankResult* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Common_RankResult>();
	}
};

}

