#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_LeaguePanel

#include "Basic.hpp"

#include "PyWidget_ModuleMainPanel_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_LeaguePanel.PyWidget_LeaguePanel
// 0x0000 (0x0618 - 0x0618)
class UPyWidget_LeaguePanel final : public UPyWidget_ModuleMainPanel
{
public:
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void OnAnimationFinished(const class UWidgetAnimation* Animation);
	void Destruct();
	void Construct();
	void OnInitialized();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_LeaguePanel">();
	}
	static class UPyWidget_LeaguePanel* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_LeaguePanel>();
	}
};

}

