#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Career_HonorBadge

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Career_HonorBadge.PyWidget_Career_HonorBadge
// 0x0000 (0x05F0 - 0x05F0)
class UPyWidget_Career_HonorBadge : public UPyMarvelUserWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Career_HonorBadge">();
	}
	static class UPyWidget_Career_HonorBadge* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Career_HonorBadge>();
	}
};

}

