#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_LobbyHeroPanel

#include "Basic.hpp"

#include "PyWidget_LobbyHero_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_LobbyHeroPanel.WBP_LobbyHeroPanel_C
// 0x0000 (0x0618 - 0x0618)
class UWBP_LobbyHeroPanel_C final : public UPyWidget_LobbyHero
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_LobbyHeroPanel_C">();
	}
	static class UWBP_LobbyHeroPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_LobbyHeroPanel_C>();
	}
};

}

